all:
	gcc -O0 -Wall -Werror -o lab3-omp-o0 lab3.c -lm -fopenmp
	gcc -O1 -Wall -Werror -o lab3-omp-o1 lab3.c -lm -fopenmp
	gcc -O2 -Wall -Werror -o lab3-omp-o2 lab3.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-o3 lab3.c -lm -fopenmp
clean:
	rm -rf lab3-omp-*
