all:
	gcc -O3 -Wall -Werror -o lab3-omp-guided-1 lab3-guided-1.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-guided-2 lab3-guided-2.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-guided-4 lab3-guided-4.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-guided-8 lab3-guided-8.c -lm -fopenmp
clean:
	rm -rf lab3-omp-*
