all:
	gcc -O3 -Wall -Werror -o lab3-omp-dynamic-1 lab3-dynamic-1.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-dynamic-2 lab3-dynamic-2.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-dynamic-4 lab3-dynamic-4.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-dynamic-8 lab3-dynamic-8.c -lm -fopenmp
clean:
	rm -rf lab3-omp-*
