all:
	gcc -O3 -Wall -Werror -o lab3-omp-static-1 lab3-static-1.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-static-2 lab3-static-2.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-static-4 lab3-static-4.c -lm -fopenmp
	gcc -O3 -Wall -Werror -o lab3-omp-static-8 lab3-static-8.c -lm -fopenmp
clean:
	rm -rf lab3-omp-*
